load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

_AUDIO_DEFCONFIG = "//private/desktop-google:intel_audio_ddk.defconfig"

ddk_module(
    name = "crc8",
    srcs = ["crc8.c"],
    out = "crc8.ko",
    kconfig = "Kconfig",
    defconfig = _AUDIO_DEFCONFIG,
    kernel_build = "//private/devices/google/common:kernel_build",
)
