load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

_AUDIO_DEFCONFIG = "//private/desktop-google:intel_audio_ddk.defconfig"

ddk_module(
    name = "snd-hda-ext-core",
    srcs = ["bus.c", "controller.c", "stream.c"],
    out = "snd-hda-ext-core.ko",
    deps = [
        "//private/desktop-google/sound/hda:snd-hda-core",
    ],
    defconfig = _AUDIO_DEFCONFIG,
    kernel_build = "//private/devices/google/common:kernel_build",
)
