# SPDX-License-Identifier: GPL-2.0-only

snd-soc-sdca-y	:= sdca_functions.o sdca_device.o sdca_regmap.o
snd-soc-sdca-irq-y := sdca_interrupts.o

obj-$(CONFIG_SND_SOC_SDCA)	+= snd-soc-sdca.o
obj-$(CONFIG_SND_SOC_SDCA_IRQ) += snd-soc-sdca-irq.o
