# SPDX-License-Identifier: GPL-2.0-only

snd-soc-sdca-objs	:= sdca_functions.o sdca_device.o sdca_function_device.o
snd-soc-sdca-smart-amp-objs := sdca_function_smart_amp.o
snd-soc-sdca-smart-mic-objs := sdca_function_smart_mic.o
snd-soc-sdca-uaj-objs := sdca_function_uaj.o
snd-soc-sdca-hid-objs := sdca_function_hid.o

obj-$(CONFIG_SND_SOC_SDCA)	+= snd-soc-sdca.o
obj-$(CONFIG_SND_SOC_SDCA_SMART_AMP)	+= snd-soc-sdca-smart-amp.o
obj-$(CONFIG_SND_SOC_SDCA_SMART_MIC)	+= snd-soc-sdca-smart-mic.o
obj-$(CONFIG_SND_SOC_SDCA_UAJ)	+= snd-soc-sdca-uaj.o
obj-$(CONFIG_SND_SOC_SDCA_HID)	+= snd-soc-sdca-hid.o
