# SPDX-License-Identifier: GPL-2.0-only

snd-soc-sdca-objs	:= sdca_functions.o sdca_device.o

obj-$(CONFIG_SND_SOC_SDCA)	+= snd-soc-sdca.o

snd-soc-sdca-irq-handler-objs	:= sdca_interrupts.o

obj-$(CONFIG_SND_SOC_SDCA_IRQ_HANDLER)	+= snd-soc-sdca-irq-handler.o
