load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

ddk_module(
    name = "mac80211",
    srcs = [
        "aead_api.c",
        "aes_cmac.c",
        "aes_gmac.c",
        "agg-rx.c",
        "agg-tx.c",
        "airtime.c",
        "cfg.c",
        "chan.c",
        "driver-ops.c",
        "eht.c",
        "ethtool.c",
        "fils_aead.c",
        "he.c",
        "ht.c",
        "ibss.c",
        "iface.c",
        "key.c",
        "led.c",
        "link.c",
        "main.c",
        "michael.c",
        "mlme.c",
        "ocb.c",
        "offchannel.c",
        "parse.c",
        "pm.c",
        "rate.c",
        "rc80211_minstrel_ht.c",
        "rx.c",
        "s1g.c",
        "scan.c",
        "spectmgmt.c",
        "sta_info.c",
        "status.c",
        "tdls.c",
        "tkip.c",
        "trace.c",
        "tx.c",
        "util.c",
        "vht.c",
        "wbrf.c",
        "wep.c",
        "wme.c",
        "wpa.c",
    ],
    out = "mac80211.ko",
    hdrs = [
        "aead_api.h",
        "aes_ccm.h",
        "aes_cmac.h",
        "aes_gcm.h",
        "aes_gmac.h",
        "debug.h",
        "debugfs.h",
        "debugfs_key.h",
        "debugfs_netdev.h",
        "debugfs_sta.h",
        "driver-ops.h",
        "drop.h",
        "fils_aead.h",
        "ieee80211_i.h",
        "key.h",
        "led.h",
        "mesh.h",
        "michael.h",
        "rate.h",
        "rc80211_minstrel_ht.h",
        "sta_info.h",
        "tkip.h",
        "trace.h",
        "trace_msg.h",
        "wep.h",
        "wme.h",
        "wpa.h",
    ],
    includes = [
        ".",
    ],
    kernel_build = "//private/devices/google/common:kernel_build",
    local_defines = [
        "CONFIG_CFG80211=1",
        "CONFIG_CFG80211_CERTIFICATION_ONUS=1",
        "CONFIG_MAC80211_DEBUG_MENU=1",
        "CONFIG_MAC80211=1",
        "CONFIG_MAC80211_VERBOSE_DEBUG=1",
        "CONFIG_MAC80211_RC_MINSTREL=1",
        "CONFIG_MAC80211_HAS_RC=1",
        "CONFIG_MAC80211_LEDS=1",
        "CONFIG_MAC80211_RC_DEFAULT_MINSTREL=1",
        "CONFIG_MAC80211_RC_DEFAULT=\"minstrel_ht\"",
        "CONFIG_MAC80211_MESSAGE_TRACING=1",
    ],
    deps = [
        "//private/desktop-google:main80211_hdrs",
        "//private/desktop-google/net/wireless:cfg80211",
    ],
)
