# SPDX-License-Identifier: GPL-2.0-only
# Copyright © 2026, Intel Corporation.

load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
)

package(
    default_visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules:__subpackages__",
    ],
)

ddk_module(
    name = "intel_vendor_hooks",
    srcs = ["intel_vendor_hooks.c"],
    out = "intel_vendor_hooks.ko",
    kernel_build = "//private/devices/google/common:kernel_build",
)
