load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_headers",
    "ddk_module",
)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

_AUDIO_DEFCONFIG = "//private/desktop-google:intel_audio_ddk.defconfig"

ddk_headers(
    name = "sof_headers",
    hdrs = glob(["*.h"]),
    includes = ["."],
    linux_includes = [
        "sound/soc/sof",
    ],
)

ddk_module(
    name = "snd-sof",
    srcs = [
        "ipc3-compress.c",
        "control.c",
        "core.c",
        "debug.c",
        "fw-file-profile.c",
        "iomem-utils.c",
        "ipc.c",
        "ipc3.c",
        "ipc3-control.c",
        "ipc3-dtrace.c",
        "ipc3-loader.c",
        "ipc3-pcm.c",
        "ipc3-priv.h",
        "ipc3-topology.c",
        "ipc4.c",
        "ipc4-control.c",
        "ipc4-fw-reg.h",
        "ipc4-loader.c",
        "ipc4-mtrace.c",
        "ipc4-pcm.c",
        "ipc4-priv.h",
        "ipc4-telemetry.c",
        "ipc4-telemetry.h",
        "ipc4-topology.c",
        "ipc4-topology.h",
        "loader.c",
        "ops.c",
        "ops.h",
        "pcm.c",
        "pm.c",
        "sof-audio.c",
        "sof-audio.h",
        "sof-client.c",
        "sof-client.h",
        "sof-of-dev.h",
        "sof-priv.h",
        "sof-utils.h",
        "stream-ipc.c",
        "topology.c",
        "trace.c",
    ],
    out = "snd-sof.ko",
    copts = [
        "-Iprivate/desktop-google/include",
        "-DCONFIG_SND_SOC_COMPRESS=1",
        "-DCONFIG_SND_SOC_SOF_COMPRESS=1",
        "-Ddomain_id=dp_domain_id",
        "-Dstack_bytes=dp_stack_bytes",
        "-Dheap_bytes=dp_heap_bytes",
    ],
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
    deps = [
        ":snd-sof-utils",
        "//private/desktop-google:sof_api_header",
        "//private/desktop-google:sof_config_header",
    ],
)

ddk_module(
    name = "snd-sof-pci",
    srcs = [
        "ipc3-priv.h",
        "ipc4-priv.h",
        "ops.h",
        "sof-audio.h",
        "sof-client.h",
        "sof-pci-dev.c",
        "sof-pci-dev.h",
        "sof-priv.h",
    ],
    out = "snd-sof-pci.ko",
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
    deps = [
        ":snd-sof",
        ":snd-sof-utils",
    ],
)

ddk_module(
    name = "snd-sof-acpi",
    srcs = [
        "ipc3-priv.h",
        "ipc4-priv.h",
        "ops.h",
        "sof-acpi-dev.c",
        "sof-acpi-dev.h",
        "sof-audio.h",
        "sof-client.h",
        "sof-priv.h",
    ],
    out = "snd-sof-acpi.ko",
    copts = [
        "-Iprivate/desktop-google/sound/soc/sof",
        "-Iprivate/desktop-google/sound/soc/intel/common",
    ],
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
    deps = [
        ":snd-sof",
        ":snd-sof-utils",
        "//private/desktop-google/sound/soc/intel/common:intel_common_headers",
        "//private/desktop-google/sound/soc/sof/intel:intel_headers",
    ],
)

ddk_module(
    name = "snd-sof-utils",
    srcs = [
        "sof-utils.c",
        "sof-utils.h",
    ],
    out = "snd-sof-utils.ko",
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
)

ddk_module(
    name = "snd-sof-probes",
    srcs = [
        "sof-client-probes.c",
        "sof-client-probes-ipc3.c",
        "sof-client-probes-ipc4.c",
    ],
    out = "snd-sof-probes.ko",
    copts = ["-Iprivate/desktop-google/sound/soc/sof"],
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
    deps = [
        ":snd-sof",
        ":sof_headers",
    ],
)

ddk_module(
    name = "snd-sof-ipc-flood-test",
    srcs = [
        "sof-client-ipc-flood-test.c",
    ],
    out = "snd-sof-ipc-flood-test.ko",
    copts = ["-Iprivate/desktop-google/sound/soc/sof"],
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
    deps = [
        ":snd-sof",
        ":sof_headers",
        "//private/desktop-google:sof_api_header",
        "//private/desktop-google:sof_config_header",
    ],
)

ddk_module(
    name = "snd-sof-ipc-msg-injector",
    srcs = [
        "sof-client-ipc-msg-injector.c",
    ],
    out = "snd-sof-ipc-msg-injector.ko",
    copts = ["-Iprivate/desktop-google/sound/soc/sof"],
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
    deps = [
        ":snd-sof",
        ":sof_headers",
        "//private/desktop-google:sof_api_header",
        "//private/desktop-google:sof_config_header",
    ],
)

ddk_module(
    name = "snd-sof-ipc-kernel-injector",
    srcs = [
        "sof-client-ipc-kernel-injector.c",
    ],
    out = "snd-sof-ipc-kernel-injector.ko",
    copts = ["-Iprivate/desktop-google/sound/soc/sof"],
    defconfig = _AUDIO_DEFCONFIG,
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
    deps = [
        ":snd-sof",
        ":sof_headers",
        "//private/desktop-google:sof_api_header",
        "//private/desktop-google:sof_config_header",
    ],
)
