load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

_AUDIO_DEFCONFIG = "//private/desktop-google:intel_audio_ddk.defconfig"

ddk_module(
    name = "cs42l43",
    srcs = [
        "cs42l43.c",
        "cs42l43.h",
    ],
    out = "cs42l43.ko",
    kconfig = "Kconfig",
    defconfig = _AUDIO_DEFCONFIG,
    kernel_build = "//private/devices/google/common:kernel_build",
)

ddk_module(
    name = "cs42l43-sdw",
    srcs = [
        "cs42l43-sdw.c",
        "cs42l43.h",
    ],
    out = "cs42l43-sdw.ko",
    deps = [
        ":cs42l43",
        "//private/desktop-google/drivers/base/regmap:regmap-sdw",
        "//private/desktop-google/drivers/soundwire:soundwire-bus",
    ],
    kconfig = "Kconfig",
    defconfig = _AUDIO_DEFCONFIG,
    kernel_build = "//private/devices/google/common:kernel_build",
)

ddk_module(
    name = "cros_ec_dev",
    srcs = [
        "cros_ec_dev.c",
    ],
    out = "cros_ec_dev.ko",
    defconfig = "defconfig_cros_ec_dev",
    kernel_build = "//private/devices/google/common:kernel_build",
)
