load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
)

package(default_visibility = ["//visibility:public"])

_AUDIO_DEFCONFIG = "//private/desktop-google:intel_audio_ddk.defconfig"


ddk_module(
    name = "snd-ctl-led",
    srcs = [
        "control_led.c",
    ],
    out = "snd-ctl-led.ko",
    kconfig = "Kconfig",
    defconfig = _AUDIO_DEFCONFIG,
    kernel_build = "//private/devices/google/common:kernel_build",
)
