load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_headers",
    "ddk_module",
)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "xe_kconfigs",
    srcs = [
        "i915/Kconfig",
        "xe/Kconfig",
        "//private/desktop-google/drivers/misc/mei:mei_kconfigs",
    ],
)

ddk_module(
    name = "drm_xe",
    srcs = [
        "xe/xe_bb.c",
        "xe/xe_bo.c",
        "xe/xe_bo_evict.c",
        "xe/xe_dep_scheduler.c",
        "xe/xe_devcoredump.c",
        "xe/xe_device.c",
        "xe/xe_device_sysfs.c",
        "xe/xe_dma_buf.c",
        "xe/xe_drm_client.c",
        "xe/xe_eu_stall.c",
        "xe/xe_exec.c",
        "xe/xe_exec_queue.c",
        "xe/xe_execlist.c",
        "xe/xe_force_wake.c",
        "xe/xe_ggtt.c",
        "xe/xe_gpu_scheduler.c",
        "xe/xe_gsc.c",
        "xe/xe_gsc_debugfs.c",
        "xe/xe_gsc_proxy.c",
        "xe/xe_gsc_submit.c",
        "xe/xe_gt.c",
        "xe/xe_gt_ccs_mode.c",
        "xe/xe_gt_clock.c",
        "xe/xe_gt_freq.c",
        "xe/xe_gt_idle.c",
        "xe/xe_gt_mcr.c",
        "xe/xe_gt_pagefault.c",
        "xe/xe_gt_sriov_vf.c",
        "xe/xe_gt_sysfs.c",
        "xe/xe_gt_throttle.c",
        "xe/xe_gt_topology.c",
        "xe/xe_guc.c",
        "xe/xe_guc_ads.c",
        "xe/xe_guc_buf.c",
        "xe/xe_guc_capture.c",
        "xe/xe_guc_ct.c",
        "xe/xe_guc_db_mgr.c",
        "xe/xe_guc_engine_activity.c",
        "xe/xe_guc_hwconfig.c",
        "xe/xe_guc_id_mgr.c",
        "xe/xe_guc_klv_helpers.c",
        "xe/xe_guc_log.c",
        "xe/xe_guc_pc.c",
        "xe/xe_guc_relay.c",
        "xe/xe_guc_submit.c",
        "xe/xe_guc_tlb_inval.c",
        "xe/xe_heci_gsc.c",
        "xe/xe_huc.c",
        "xe/xe_hw_engine.c",
        "xe/xe_hw_engine_class_sysfs.c",
        "xe/xe_hw_engine_group.c",
        "xe/xe_hw_error.c",
        "xe/xe_hw_fence.c",
        "xe/xe_irq.c",
        "xe/xe_late_bind_fw.c",
        "xe/xe_lrc.c",
        "xe/xe_memirq.c",
        "xe/xe_migrate.c",
        "xe/xe_mmio.c",
        "xe/xe_mmio_gem.c",
        "xe/xe_mocs.c",
        "xe/xe_module.c",
        "xe/xe_nvm.c",
        "xe/xe_oa.c",
        "xe/xe_observation.c",
        "xe/xe_pat.c",
        "xe/xe_pci.c",
        "xe/xe_pcode.c",
        "xe/xe_pm.c",
        "xe/xe_preempt_fence.c",
        "xe/xe_psmi.c",
        "xe/xe_pt.c",
        "xe/xe_pt_walk.c",
        "xe/xe_pxp.c",
        "xe/xe_pxp_debugfs.c",
        "xe/xe_pxp_multi_session.c",
        "xe/xe_pxp_submit.c",
        "xe/xe_query.c",
        "xe/xe_range_fence.c",
        "xe/xe_reg_sr.c",
        "xe/xe_reg_whitelist.c",
        "xe/xe_ring_ops.c",
        "xe/xe_rtp.c",
        "xe/xe_sa.c",
        "xe/xe_sched_job.c",
        "xe/xe_shrinker.c",
        "xe/xe_sriov.c",
        "xe/xe_sriov_vf.c",
        "xe/xe_sriov_vf_ccs.c",
        "xe/xe_step.c",
        "xe/xe_survivability_mode.c",
        "xe/xe_sync.c",
        "xe/xe_tile.c",
        "xe/xe_tile_sriov_vf.c",
        "xe/xe_tile_sysfs.c",
        "xe/xe_tlb_inval.c",
        "xe/xe_tlb_inval_job.c",
        "xe/xe_trace.c",
        "xe/xe_trace_bo.c",
        "xe/xe_trace_guc.c",
        "xe/xe_trace_lrc.c",
        "xe/xe_ttm_stolen_mgr.c",
        "xe/xe_ttm_sys_mgr.c",
        "xe/xe_ttm_vram_mgr.c",
        "xe/xe_tuning.c",
        "xe/xe_uc.c",
        "xe/xe_uc_fw.c",
        "xe/xe_validation.c",
        "xe/xe_vm.c",
        "xe/xe_vm_madvise.c",
        "xe/xe_vram.c",
        "xe/xe_vram_freq.c",
        "xe/xe_vsec.c",
        "xe/xe_wa.c",
        "xe/xe_wait_user_fence.c",
        "xe/xe_wopcm.c",
    ],
    out = "xe.ko",
    hdrs = glob(
        [
            "**/*.h",
        ],
    ),
    conditional_srcs = {
        "CONFIG_I2C": {
            True: ["xe/xe_i2c.c"],
        },
        "CONFIG_DRM_XE_GPUFREQTRACER": {
            True: ["xe/xe_gpufreqtracer.c"],
        },
        "CONFIG_DRM_XE_GPUSVM": {
            True: ["xe/xe_svm.c"],
        },
        "CONFIG_DRM_GPUSVM": {
            True: ["xe/xe_userptr.c"],
        },
        "CONFIG_HWMON": {
            True: ["xe/xe_hwmon.c"],
        },
        "CONFIG_PERF_EVENTS": {
            True: ["xe/xe_pmu.c"],
        },
        "CONFIG_CONFIGFS_FS": {
            True: ["xe/xe_configfs.c"],
        },
        "CONFIG_PCI_IOV": {
            True: [
                "xe/xe_gt_sriov_pf.c",
                "xe/xe_gt_sriov_pf_config.c",
                "xe/xe_gt_sriov_pf_control.c",
                "xe/xe_gt_sriov_pf_migration.c",
                "xe/xe_gt_sriov_pf_monitor.c",
                "xe/xe_gt_sriov_pf_policy.c",
                "xe/xe_gt_sriov_pf_service.c",
                "xe/xe_lmtt.c",
                "xe/xe_lmtt_2l.c",
                "xe/xe_lmtt_ml.c",
                "xe/xe_pci_sriov.c",
                "xe/xe_sriov_pf.c",
                "xe/xe_sriov_pf_service.c",
            ],
        },
        "CONFIG_DRM_XE_KUNIT_TEST": {
            True: ["xe/tests/xe_kunit_helpers.c"],
        },
        "CONFIG_DRM_XE_DISPLAY": {
            True: [
                "xe/display/ext/i915_irq.c",
                "xe/display/ext/i915_utils.c",
                "xe/display/intel_bo.c",
                "xe/display/intel_fb_bo.c",
                "xe/display/intel_fbdev_fb.c",
                "xe/display/xe_display.c",
                "xe/display/xe_display_misc.c",
                "xe/display/xe_display_rpm.c",
                "xe/display/xe_display_wa.c",
                "xe/display/xe_dsb_buffer.c",
                "xe/display/xe_fb_pin.c",
                "xe/display/xe_hdcp_gsc.c",
                "xe/display/xe_panic.c",
                "xe/display/xe_plane_initial.c",
                "xe/display/xe_tdf.c",
                "i915/soc/intel_dram.c",
                "i915/soc/intel_rom.c",
                "i915/display/icl_dsi.c",
                "i915/display/intel_alpm.c",
                "i915/display/intel_atomic.c",
                "i915/display/intel_audio.c",
                "i915/display/intel_backlight.c",
                "i915/display/intel_bios.c",
                "i915/display/intel_bw.c",
                "i915/display/intel_cdclk.c",
                "i915/display/intel_cmtg.c",
                "i915/display/intel_color.c",
                "i915/display/intel_colorop.c",
                "i915/display/intel_color_pipeline.c",
                "i915/display/intel_combo_phy.c",
                "i915/display/intel_connector.c",
                "i915/display/intel_crtc.c",
                "i915/display/intel_crtc_state_dump.c",
                "i915/display/intel_cursor.c",
                "i915/display/intel_cx0_phy.c",
                "i915/display/intel_ddi.c",
                "i915/display/intel_ddi_buf_trans.c",
                "i915/display/intel_display.c",
                "i915/display/intel_display_conversion.c",
                "i915/display/intel_display_device.c",
                "i915/display/intel_display_driver.c",
                "i915/display/intel_display_irq.c",
                "i915/display/intel_display_params.c",
                "i915/display/intel_display_power.c",
                "i915/display/intel_display_power_map.c",
                "i915/display/intel_display_power_well.c",
                "i915/display/intel_display_trace.c",
                "i915/display/intel_display_wa.c",
                "i915/display/intel_dkl_phy.c",
                "i915/display/intel_dmc.c",
                "i915/display/intel_dmc_wl.c",
                "i915/display/intel_dp.c",
                "i915/display/intel_dp_aux.c",
                "i915/display/intel_dp_aux_backlight.c",
                "i915/display/intel_dp_hdcp.c",
                "i915/display/intel_dp_link_training.c",
                "i915/display/intel_dp_mst.c",
                "i915/display/intel_dp_test.c",
                "i915/display/intel_dpll.c",
                "i915/display/intel_dpll_mgr.c",
                "i915/display/intel_dpt_common.c",
                "i915/display/intel_drrs.c",
                "i915/display/intel_dsb.c",
                "i915/display/intel_dsi.c",
                "i915/display/intel_dsi_dcs_backlight.c",
                "i915/display/intel_dsi_vbt.c",
                "i915/display/intel_encoder.c",
                "i915/display/intel_fb.c",
                "i915/display/intel_fbc.c",
                "i915/display/intel_fdi.c",
                "i915/display/intel_fifo_underrun.c",
                "i915/display/intel_flipq.c",
                "i915/display/intel_frontbuffer.c",
                "i915/display/intel_global_state.c",
                "i915/display/intel_gmbus.c",
                "i915/display/intel_hdcp.c",
                "i915/display/intel_hdcp_gsc_message.c",
                "i915/display/intel_hdmi.c",
                "i915/display/intel_hotplug.c",
                "i915/display/intel_hotplug_irq.c",
                "i915/display/intel_hti.c",
                "i915/display/intel_link_bw.c",
                "i915/display/intel_lspcon.c",
                "i915/display/intel_modeset_lock.c",
                "i915/display/intel_modeset_setup.c",
                "i915/display/intel_modeset_verify.c",
                "i915/display/intel_panel.c",
                "i915/display/intel_pfit.c",
                "i915/display/intel_plane.c",
                "i915/display/intel_pmdemand.c",
                "i915/display/intel_pch.c",
                "i915/display/intel_pps.c",
                "i915/display/intel_psr.c",
                "i915/display/intel_qp_tables.c",
                "i915/display/intel_quirks.c",
                "i915/display/intel_snps_hdmi_pll.c",
                "i915/display/intel_snps_phy.c",
                "i915/display/intel_tc.c",
                "i915/display/intel_vblank.c",
                "i915/display/intel_vdsc.c",
                "i915/display/intel_vga.c",
                "i915/display/intel_vrr.c",
                "i915/display/intel_wm.c",
                "i915/display/skl_prefill.c",
                "i915/display/skl_scaler.c",
                "i915/display/skl_universal_plane.c",
                "i915/display/skl_watermark.c",
            ],
        },
        "CONFIG_ACPI": {
            True: [
                "i915/display/intel_acpi.c",
                "i915/display/intel_opregion.c",
            ],
        },
        "CONFIG_DRM_FBDEV_EMULATION": {
            True: [
                "i915/display/intel_fbdev.c",
            ],
        },
        "CONFIG_DEBUG_FS": {
            True: [
                "xe/xe_debugfs.c",
                "xe/xe_gt_debugfs.c",
                "xe/xe_gt_sriov_vf_debugfs.c",
                "xe/xe_gt_stats.c",
                "xe/xe_guc_debugfs.c",
                "xe/xe_huc_debugfs.c",
                "xe/xe_tile_debugfs.c",
                "xe/xe_uc_debugfs.c",
                "xe/xe_gt_sriov_pf_debugfs.c",
                "i915/display/intel_display_debugfs.c",
                "i915/display/intel_display_debugfs_params.c",
                "i915/display/intel_pipe_crc.c",
            ],
        },
        "CONFIG_DRM_XE_DP_TUNNEL": {
            True: [
                "i915/display/intel_dp_tunnel.c",
            ],
        },
    },
    defconfig = "defconfig_xe",
    includes = [
        ".",
        "i915/display",
        "xe",
        "xe/compat-i915-headers",
        "xe/display",
        "xe/display/ext",
        "xe/generated",
    ],
    kconfig = ":xe_kconfigs",
    kernel_build = "//private/devices/google/common:kernel_build",
    local_defines = [
        "drm_i915_private=xe_device",
    ],
    deps = [
        ":xe_generated_hdrs",
        "//private/desktop-google:drm_xe_uapi_includes",
        "//private/desktop-google:xe_global_includes",
        "//private/desktop-google/drivers/gpu/drm/display:drm_display_helper",
    ],
)

ddk_headers(
    name = "xe_generated_hdrs",
    hdrs = [
        ":generate_device_wa_oob",
        ":generate_wa_oob",
    ],
    includes = ["xe"],
)

cc_binary(
    name = "xe_gen_wa_oob",
    srcs = ["xe/xe_gen_wa_oob.c"],
)

# Generating the OOB files
genrule(
    name = "generate_wa_oob",
    srcs = ["xe/xe_wa_oob.rules"],
    outs = [
        "xe/generated/xe_wa_oob.c",
        "xe/generated/xe_wa_oob.h",
    ],
    cmd = "$(location :xe_gen_wa_oob) $(location :xe/xe_wa_oob.rules) $(OUTS)",
    tools = [":xe_gen_wa_oob"],
)

# Generating the Device OOB files
genrule(
    name = "generate_device_wa_oob",
    srcs = ["xe/xe_device_wa_oob.rules"],
    outs = [
        "xe/generated/xe_device_wa_oob.c",
        "xe/generated/xe_device_wa_oob.h",
    ],
    cmd = "$(location :xe_gen_wa_oob) $(location :xe/xe_device_wa_oob.rules) $(OUTS)",
    tools = [":xe_gen_wa_oob"],
)
