# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026 The Android Open Source Project

load(
    "//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

ddk_module(
    name = "cros_ec_pwrmon",
    srcs = [
        "cros_ec_pwrmon.c",
    ],
    out = "cros_ec_pwrmon.ko",
    hdrs = [
        "cros_ec_pwrmon.h",
    ],
    defconfig = "configs/defconfig_cros_ec_pwrmon",
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel_build",
)
